#
# Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')
import sys

env = BuildEnv.Clone()

env.Append(CPPPATH = [env['TOP'],
                      env['TOP'] + '/io',
                     ])

env.Append(LIBPATH = env['TOP'] + '/base')
env.Append(LIBPATH = env['TOP'] + '/base/test')
env.Append(LIBPATH = env['TOP'] + '/bgp')
env.Append(LIBPATH = env['TOP'] + '/bgp/inet')
env.Append(LIBPATH = env['TOP'] + '/bgp/inet6')
env.Append(LIBPATH = env['TOP'] + '/bgp/evpn')
env.Append(LIBPATH = env['TOP'] + '/bgp/ermvpn')
env.Append(LIBPATH = env['TOP'] + '/bgp/test')
env.Append(LIBPATH = env['TOP'] + '/bgp/l3vpn')
env.Append(LIBPATH = env['TOP'] + '/bgp/inet6')
env.Append(LIBPATH = env['TOP'] + '/bgp/inet6vpn')
env.Append(LIBPATH = env['TOP'] + '/bgp/origin-vn')
env.Append(LIBPATH = env['TOP'] + '/bgp/routing-instance')
env.Append(LIBPATH = env['TOP'] + '/bgp/rtarget')
env.Append(LIBPATH = env['TOP'] + '/bgp/security_group')
env.Append(LIBPATH = env['TOP'] + '/bgp/tunnel_encap')
env.Append(LIBPATH = env['TOP'] + '/control-node')
env.Append(LIBPATH = env['TOP'] + '/db')
env.Append(LIBPATH = env['TOP'] + '/io')
env.Append(LIBPATH = env['TOP'] + '/ifmap')
env.Append(LIBPATH = env['TOP'] + '/net')
env.Append(LIBPATH = env['TOP'] + '/route')
env.Append(LIBPATH = env['TOP'] + '/xmpp')
env.Append(LIBPATH = env['TOP'] + '/xml')
env.Append(LIBPATH = env['TOP'] + '/schema')
env.Append(LIBPATH = env['TOP'] + '/bgp/extended-community')

env.Prepend(LIBS = [
                    'task_test',
                    'bgptest',
                    'bgp',
                    'peer_sandesh',
                    'control_node',
                    'origin_vn',
                    'routing_instance',
                    'rtarget',
                    'security_group',
                    'tunnel_encap',
                    'ifmap_vnc',
                    'bgp_schema',
                    'sandesh',
                    'http',
                    'http_parser',
                    'curl',
                    'ifmap_server',
                    'ifmap_common',
                    'base',
                    'db',
                    'gunit',
                    'io',
                    'sandeshvns',
                    'net',
                    'route',
                    'xmpp',
                    'bgp_inet',
                    'bgp_inet6',
                    'bgp_ermvpn',
                    'bgp_evpn',
                    'bgp_l3vpn',
                    'bgp_inet6',
                    'bgp_inet6vpn',
                    'xmpp_unicast',
                    'xmpp_multicast',
                    'xmpp_enet',
                    'xml',
                    'pugixml',
                    'boost_regex',
                    'process_info',
                    'extended_community'
                    ])

if sys.platform != 'darwin':
    env.Append(LIBS=['rt'])
    env.Prepend(LINKFLAGS = ['-Wl,--whole-archive',
                             '-lbgp_inet',
                             '-lbgp_evpn',
                             '-lbgp_l3vpn',
                             '-lbgp_inet6',
                             '-lbgp_inet6vpn',
                             '-lrtarget',
                             '-lbgp_ermvpn',
                             '-ltask_test',
                             '-Wl,--no-whole-archive'])

inet6vpn_prefix_test = env.UnitTest('inet6vpn_prefix_test',
                                    ['inet6vpn_prefix_test.cc'])
env.Alias('src/bgp/inet6vpn:inet6vpn_prefix_test', inet6vpn_prefix_test)
env.Alias('controller/src/bgp/inet6vpn:inet6vpn_prefix_test',
          inet6vpn_prefix_test)

inet6vpn_route_test = env.UnitTest('inet6vpn_route_test',
                                   ['inet6vpn_route_test.cc'])
env.Alias('src/bgp/inet6vpn:inet6vpn_route_test', inet6vpn_route_test)
env.Alias('controller/src/bgp/inet6vpn:inet6vpn_route_test',
          inet6vpn_route_test)

inet6vpn_table_test = env.UnitTest('inet6vpn_table_test',
                                   ['inet6vpn_table_test.cc'])
env.Alias('src/bgp/inet6vpn:inet6vpn_table_test', inet6vpn_table_test)
env.Alias('controller/src/bgp/inet6vpn:inet6vpn_table_test',
          inet6vpn_table_test)

test_suite = [
    inet6vpn_prefix_test,
    inet6vpn_route_test,
    inet6vpn_table_test,
]

test = env.TestSuite('bgp-test', test_suite)
env.Alias('controller/src/bgp/inet6vpn:test', test)

Return('test_suite')
