# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
Import('CfgmEnv')
env = CfgmEnv.Clone()

setup_sources = [
           'setup.py',
           'MANIFEST.in',
          ]

setup_sources_rules = []
for file in setup_sources:
    setup_sources_rules.append(env.Install(Dir('.'), File(file).srcnode()))

local_sources = [
                  '__init__.py',
                  'discovery.py',
                  'exceptions.py',
                  'imid.py',
                  'svc_info.py',
                  'vnc_cpu_info.py',
                  'rest.py',
                  'test_utils.py',
                  'vnc_plugin_base.py',
                  'vnc_extensions.py',
                 ]


local_sources_rules = []
for file in local_sources:
    local_sources_rules.append(env.Install("cfgm_common", File(file).srcnode()))

ifmap_sources = [ 'ifmap' ]
ifmap_sources_rules = []
for file in ifmap_sources:
    ifmap_sources_rules.append(env.Install("cfgm_common/", "#/third_party/ifmap-python-client/" + file))

sandesh_dirs = [ 'service_instance', 'vnc_api', 'virtual_machine', 'virtual_network', 'acl', 'vrouter', 'cfgm_cpuinfo']
for file in sandesh_dirs:
    Dir('../uve/gen_py/' + file)
sandesh_files = sandesh_dirs
sandesh_sources = ['gen_py/' + ssrc for ssrc in sandesh_files]
sandesh_sources_rules = []

for file in sandesh_sources:
    sandesh_sources_rules.append(env.Install("cfgm_common/uve", "../uve/" + file))
env.Depends(sandesh_sources_rules, '../uve/gen_py')

sandesh_init_rules = [env.Install("cfgm_common/uve", "../uve/gen_py/__init__.py")]
env.Requires(sandesh_init_rules, sandesh_sources_rules)

# Generate the sandesh cpuinfo from base
sandesh_base_gen_py_files = env.SandeshGenPy('#/controller/src/base/sandesh/cpuinfo.sandesh')
sandesh_base_dirs = [ 'cpuinfo' ]
for file in sandesh_base_dirs:
    Dir('gen_py/' + file)

sandesh_base_files = sandesh_base_dirs
sandesh_base_sources = ['gen_py/' + ssrc for ssrc in sandesh_base_files]
sandesh_base_sources_rules = []

for file in sandesh_base_sources:
    sandesh_base_sources_rules.append(env.Install("cfgm_common/uve/cfgm_cpuinfo/", file))
env.Depends(sandesh_base_sources_rules, sandesh_base_gen_py_files)

rel_path = Dir('cfgm_common').path
def BuildInfoAction(target, source, env):
    env.GenerateBuildInfoPyCode(path=rel_path)
    
build_info_rules = [env.Command(target='buildinfo.py', source = None, action=BuildInfoAction)]

sdist_depends = []
sdist_depends.extend(setup_sources_rules)
sdist_depends.extend(local_sources_rules)
sdist_depends.extend(ifmap_sources_rules)
sdist_depends.extend(sandesh_sources_rules)
sdist_depends.extend(sandesh_init_rules)
sdist_depends.extend(sandesh_base_sources_rules)
sdist_depends.extend(build_info_rules)
sdist_gen = env.Command('dist', 'setup.py', 'python setup.py sdist', chdir=1)

env.Depends(sdist_gen, sdist_depends)
env.Default(sdist_gen)

