#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])

libbgp_l3vpn = env.Library('bgp_l3vpn',
                           ['inetvpn_address.cc',
                            'inetvpn_table.cc',
                            'inetvpn_route.cc'
                            ])

l3vpn_test_cases = env.SConscript('test/SConscript', exports='BuildEnv',
                                  duplicate = 0)
Return('l3vpn_test_cases')
