# -*- mode: python; -*-

vpath = '#/third_party/libipfix_110209'

env = DefaultEnvironment()

version = '.1.0'

libs = [ str(File('#/build/lib/libipfix' + env['LIBSUFFIX'])) ]

shlibs = [ str(File('#/build/lib/libipfix.so.1.0' + env['SHLIBSUFFIX'] + version)) ]

products = libs + shlibs

config_opts = '--prefix=' + str(Dir('#/build')) + ' --includedir=' + str(Dir('#/build')) + '/include/ipfix'

cmd = ('(rm -rf ' + str(Dir('#/build')) + '/third_party/ipfix' +
       '; cp -r ' + str(Dir(vpath)) + ' ' + str(Dir('#/build')) + '/third_party/ipfix/' +
       '; cd ' + Dir('.').abspath + '; ' + Dir('.').abspath +
       '/configure' + ' ' + config_opts + '; make clean; make; make install)')

libipfix_cfg = env.Command('config.status', str(Dir(vpath)), cmd)

env.SideEffect(products, libipfix_cfg)

env.Alias('install', env.Install(env['INSTALL_LIB'], shlibs))

env.Alias('install',
          env.Symlink(env['INSTALL_LIB'] + '/libipfix.so',
                      env['INSTALL_LIB'] + '/libipfix.so' + version))
