# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
# src directory

Import('BuildEnv')

BuildEnv.SConscript('monitoring/ipmi/SConscript',
                    exports='BuildEnv',
                    duplicate=0)
