#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
import re
Import('AgentEnv')
env = AgentEnv.Clone()

# test specific modifications
AgentEnv.MakeTestEnv(env)

oper_test_suite = []
oper_flaky_test_suite = []

test_intf = AgentEnv.MakeTestCmd(env, 'test_intf', oper_test_suite)
test_vrf_assign = AgentEnv.MakeTestCmd(env, 'test_vrf_assign', oper_test_suite)
test_linklocal = AgentEnv.MakeTestCmd(env, 'test_linklocal', oper_flaky_test_suite)
test_inet_interface = AgentEnv.MakeTestCmd(env, 'test_inet_interface',
                                           oper_test_suite)
test_fabric_interface = AgentEnv.MakeTestCmd(env, 'test_fabric_interface',
                                             oper_flaky_test_suite)
test_aap = AgentEnv.MakeTestCmd(env, 'test_aap', oper_flaky_test_suite)

env.Append(LIBPATH = [
        '../../../../base/test',
        '../../../../db/test',
        '../../../../ifmap/test',
])

env.Append(LIBS = [
        'dbtest',
        'ifmap_test_util',
        'ifmap_test_util_agent',
        'task_test',
        ])

ifmap_dependency_manager_test = env.UnitTest(
        'ifmap_dependency_manager_test',
        ['ifmap_dependency_manager_test.cc'])

env.Alias('agent:ifmap_dependency_manager_test',
          ifmap_dependency_manager_test)
oper_flaky_test_suite.append(ifmap_dependency_manager_test)

namespace_manager_test = env.UnitTest(
    'namespace_manager_test',
    ['namespace_manager_test.cc'])
env.Alias('agent:namespace_manager_test', namespace_manager_test)
oper_flaky_test_suite.append(namespace_manager_test)

loadbalancer_test = env.UnitTest(
    'loadbalancer_test',
    ['loadbalancer_test.cc'])
env.Alias('agent:loadbalancer_test', loadbalancer_test)
oper_flaky_test_suite.append(loadbalancer_test)

loadbalancer_haproxy_test = env.UnitTest(
    'loadbalancer_haproxy_test',
    ['loadbalancer_haproxy_test.cc'])
env.Alias('agent:loadbalancer_haproxy_test', loadbalancer_haproxy_test)
oper_flaky_test_suite.append(loadbalancer_test)

flaky_test = env.TestSuite('agent-flaky-test', oper_flaky_test_suite)
env.Alias('controller/src/vnsw/agent/oper:flaky_test', flaky_test)

test = env.TestSuite('agent-test', oper_test_suite)
env.Alias('agent:oper', test)
env.Alias('controller/src/vnsw/agent/oper:test', test)
Return('oper_test_suite')
