# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
# src directory

import os
import re
import sys

Import('BuildEnv')

CfgmEnv = BuildEnv.Clone()

# Documentation
CfgmDocFiles = []
CfgmDocFiles += CfgmEnv['BASE_DOC_FILES']
CfgmDocFiles += CfgmEnv['SANDESH_DOC_FILES']
CfgmEnv['CFGM_DOC_FILES'] = CfgmDocFiles

#
# Deprecated
# Builds into build/<optimization>
#
subdirs=[
    'kube-manager',
]

CfgmEnv.SConscript(dirs=subdirs, exports='CfgmEnv', duplicate = 0)

#
# Build into build/noarch
#
noarch_subdirs = [
    'kube-manager',
]
for sdir in noarch_subdirs:
    CfgmEnv.SConscript('%s/SConscript' % sdir, exports='CfgmEnv',
                       variant_dir='#build/noarch/container/%s' % sdir,
                       duplicate = 1)
