# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
# src directory

Import('BuildEnv')

CfgmEnv = BuildEnv.Clone()

# Documentation
CfgmDocFiles = []
CfgmDocFiles += CfgmEnv['BASE_DOC_FILES']
CfgmDocFiles += CfgmEnv['SANDESH_DOC_FILES']
CfgmEnv['CFGM_DOC_FILES'] = CfgmDocFiles

#
# Deprecated
# Builds into build/<optimization>
#
subdirs=[
    'kube-manager',
    'mesos-manager',
    'cni',
]

CfgmEnv.SConscript(dirs=subdirs, exports='CfgmEnv', duplicate = 0)
