#
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
import re
Import('AgentEnv')
env = AgentEnv.Clone()

# test specific modifications
AgentEnv.MakeTestEnv(env)

env.Append(LIBPATH = env['TOP'] + '/vnsw/agent/test-xml')
env.Append(LIBPATH = env['TOP'] + '/vnsw/agent/mac_learning/test')
env.Append(LIBS = 'agent_test_xml')

mac_learning_test_suite = []
test_local_mac_learning = AgentEnv.MakeTestCmd(env, 'test_local_mac_learning',
                                               mac_learning_test_suite)
test_mac_aging = AgentEnv.MakeTestCmd(env, 'test_mac_aging',
                                      mac_learning_test_suite)
test_pbb_route = AgentEnv.MakeTestCmd(env, 'test_pbb_route', mac_learning_test_suite);
test = env.TestSuite('agent-test', mac_learning_test_suite)
env.TestSuite('agent:mac_learning_test', mac_learning_test_suite)
Return('mac_learning_test_suite')
