#
# Copyright (c) 2015 Juniper Networks, Inc. All rights reserved.
#

Import('DbEnv')
env = DbEnv.Clone()

subdirs = ['cql']

for dir in subdirs:
    DbEnv.SConscript(dir + '/SConscript', exports='DbEnv', duplicate=0)
