/*
 * Copyright (c) 2015 Juniper Networks, Inc. All rights reserved.
 */

#ifndef SRC_BGP_EXTENDED_COMMUNITY_TYPES_H_
#define SRC_BGP_EXTENDED_COMMUNITY_TYPES_H_

#define BGP_EXTENDED_COMMUNITY_TYPE_TWO_OCTET_AS         0x00

#define BGP_EXTENDED_COMMUNITY_TYPE_IPV4_ADDRESS         0x01

#define BGP_EXTENDED_COMMUNITY_TYPE_FOUR_OCTET_AS        0x02

#define BGP_EXTENDED_COMMUNITY_SUBTYPE_ROUTE_TARGET      0x02
#define BGP_EXTENDED_COMMUNITY_SUBTYPE_ROUTE_ORIGIN      0x03

#define BGP_EXTENDED_COMMUNITY_TYPE_OPAQUE            0x03
#define BGP_EXTENDED_COMMUNITY_OPAQUE_TUNNEL_ENCAP    0x0C
#define BGP_EXTENDED_COMMUNITY_OPAQUE_DEFAULT_GATEWAY 0x0D
#define BGP_EXTENDED_COMMUNITY_OPAQUE_LOAD_BALANCE    0x0E // TBA

#define BGP_EXTENDED_COMMUNITY_TYPE_EVPN           0x06
#define BGP_EXTENDED_COMMUNITY_EVPN_MAC_MOBILITY   0x00
#define BGP_EXTENDED_COMMUNITY_EVPN_ESI_MPLS_LABEL 0x01
#define BGP_EXTENDED_COMMUNITY_EVPN_ES_IMPORT      0x02

#define BGP_EXTENDED_COMMUNITY_TYPE_EXPERIMENTAL      0x80
#define BGP_EXTENDED_COMMUNITY_EXPERIMENTAL_ORIGIN_VN 0x71
#define BGP_EXTENDED_COMMUNITY_EXPERIMENTAL_SG_ID     0x04



#endif // SRC_BGP_EXTENDED_COMMUNITY_TYPES_H_
