import os

env = DefaultEnvironment()

openssl_path = os.environ['OPENSSL_ROOT']

env.InstallAs('#build/lib/ssl.lib', openssl_path + '/lib/ssleay32.lib')
env.InstallAs('#build/lib/crypto.lib', openssl_path + '/lib/libeay32.lib')
