import os
import sys

env = DefaultEnvironment()

openssl_root = os.getenv('OPENSSL_ROOT')
if openssl_root is None:
    print('OPENSSL_ROOT environment variable is not set')
    sys.exit(1)

env.InstallAs('#build/lib/ssl.lib', openssl_root + '/lib/ssleay32.lib')
env.InstallAs('#build/lib/crypto.lib', openssl_root + '/lib/libeay32.lib')
