# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
Import('CfgmEnv')
env = CfgmEnv.Clone()

subdirs=[
    'kube_cni',
    'mesos_cni',
]

env.SConscript(dirs=subdirs, exports='CfgmEnv', duplicate = 0)
