#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

sources = [ 'agent_init.cc' ]
libvnswinit = env.Library('vnswinit', sources)

sources = [ 'agent_init.cc', 'contrail_init_common.cc' ]
libcontrail_init_common = env.Library('contrail_init_common', sources)
