#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])

libbgp_evpn = env.Library('bgp_evpn',
                  ['evpn_route.cc',
                   'evpn_table.cc'
                  ])

evpn_unit_tests = env.SConscript('test/SConscript', exports='BuildEnv',
                                 duplicate = 0)
Return('evpn_unit_tests')
