#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])
env.Append(CPPPATH = [env['TOP'] + '/ifmap'])
env.Append(CPPPATH = [env['TOP'] + '/base/sandesh'])

libbgp_inet = env.Library('bgp_inet',
                       ['inet_route.cc',
                        'inet_table.cc'
                        ])

inet_unit_tests = env.SConscript('test/SConscript', exports='BuildEnv',
                                 duplicate = 0)
Return('inet_unit_tests')
