#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
# nova-info directory

import sys
if sys.platform == 'darwin':
    Return()

import os
Import('AgentEnv')
env = AgentEnv.Clone()

env = AgentEnv.RemoveExceptionFlag(env)
env.AppendUnique(CCFLAGS='-Wno-reorder')
env.AppendUnique(CCFLAGS='-Wno-return-type')
env.AppendUnique(CCFLAGS='-Wno-unused-variable')

targets = env.ThriftGenCpp('instance_service.thrift', True)
lib_srcs = env.ExtractCpp(targets)

libnova_ins_thrift = env.Library('nova_ins_thrift', lib_srcs)

libnova_ins = env.Library('nova_ins',
                           ['instance_service_server.cc',])

subdirs = ['test']
for dir in subdirs:
    env.SConscript(dir + '/SConscript', exports='AgentEnv', duplicate=0)
