#
# Copyright (c) 2015 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])
env.Append(CPPPATH = [env['TOP'] + '/bgp'])
env.Append(CPPPATH = [env['TOP'] + '/db'])
env.Append(CPPPATH = [env['TOP'] + '/io'])

# Generate the source files
SandeshGenFiles = env.SandeshGenCpp('routing_policy.sandesh')
SandeshGenFiles += env.SandeshGenOnlyCpp('routing_policy_internal.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)

librouting_policy = env.Library('routing_policy', SandeshGenSrcs +
                                ['routing_policy.cc',
                                'routing_policy_action.cc',
                                'routing_policy_match.cc',
                                'show_routing_policy.cc'])

