#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')
import sys

env = BuildEnv.Clone()
env.AppendUnique(CCFLAGS='-fno-exceptions')
env.Append(CPPPATH = [env['TOP']])

env.Append(LIBPATH = ['#/' + Dir('..').path,
                      '../../base'])

env.Append(LIBPATH = env['TOP'] + '/base/test')

env.Prepend(LIBS = ['gunit', 'task_test', 'sandesh', 'http', 'sandeshvns', 'io', 'base',
                    'http_parser', 'curl', 'boost_program_options'])

if sys.platform != 'darwin':
    env.Append(LIBS = ['rt'])

tcp_server_test = env.UnitTest('tcp_server_test',
                              ['tcp_server_test.cc'],
                              )

env.Alias('src/io:tcp_server_test', tcp_server_test)

tcp_io_test = env.UnitTest('tcp_io_test',
                           ['tcp_io_test.cc'],
                         )

env.Alias('src/io:tcp_io_test', tcp_io_test)


tcp_stress_test = env.UnitTest('tcp_stress_test',
                           ['tcp_stress_test.cc'],
                         )

env.Alias('src/io:tcp_stress_test', tcp_stress_test)


# netlink_test = env.Program('netlink_test', ['netlink_test.cc'])
# env.Alias('src/io:netlink_test', netlink_test)

test_suite = [
    tcp_server_test,
    tcp_io_test,
    tcp_stress_test,
    ]

test = env.TestSuite('io-test', test_suite)
env.Alias('src/io:test', test)
Return('test_suite')
