#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import re
Import('AgentEnv')
env = AgentEnv.Clone()
AgentEnv.MakeTestEnv(env)
flow_manager_suite=[]
#FlowStatsSandeshGenFiles = env.SandeshGenCpp('flow_stats_interval.sandesh')
#FlowStatsSandeshGenSrcs = env.ExtractCpp(FlowStatsSandeshGenFiles)
#FlowStatsSandeshGenObjs = env.Object(FlowStatsSandeshGenSrcs)

# test specific modifications
AgentEnv.MakeTestEnv(env)

flow_stats_test_suite=[]
flow_stats_flaky_test_suite=[]

test_session_stats = AgentEnv.MakeTestCmd(env, 'test_session_stats',
                                       flow_stats_test_suite)

test = env.TestSuite('agent-test', flow_stats_test_suite)
env.Alias('agent:flow_stats', test)
env.Alias('controller/src/vnsw/agent/vrouter/flow_stats:test', test)
Return('flow_stats_test_suite')
