#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])
env.Append(CPPPATH = [env['TOP'] + '/bgp'])
env.Append(CPPPATH = [env['TOP'] + '/io'])

librtarget = env.Library('rtarget', 
                         [ 'rtarget_prefix.cc',
                         'rtarget_address.cc',
                         'rtarget_route.cc',
                         'rtarget_table.cc'])
                     
rtarget_test_cases = env.SConscript('test/SConscript', exports='BuildEnv',
                                    duplicate = 0)
Return('rtarget_test_cases')
