#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()

librtarget = env.Library('rtarget', ['rtarget_address.cc'])
                     
rtarget_test_cases = env.SConscript('test/SConscript', exports='BuildEnv',
                                    duplicate = 0)
Return('rtarget_test_cases')
