# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#


Import('BuildEnv')
env = BuildEnv.Clone()

autogen_infra_sources = [
                 '#/tools/generateds/generateDS.py',
                 '#/tools/generateds/TypeGenerator.py',
                 '#/tools/generateds/ccsvc.py',
                 '#/tools/generateds/idl_parser.py',
                 '#/tools/generateds/ServiceGenerator.py',
                ]
autogen_sources = [
                 '#controller/src/schema/services.xsd',
                ]

# generate classes from services XML specification
autogen_script = './tools/generateds/generateDS.py'
autogen_cmd = autogen_script + \
            ' -f -l py -o ' + env['TOP'][1:] + '/discovery/client/discoveryclient/services -g service'
generated_files = [ 'services.py' ]
generated_rule = env.Command(generated_files,
                             '#controller/src/schema/services.xsd',
                             autogen_cmd + ' $SOURCE')

setup_sources = [
           'setup.py',
           'MANIFEST.in',
          ]
setup_sources_rules = []
for file in setup_sources:
    setup_sources_rules.append(env.Install("", "#controller/src/discovery/client/" + file))

local_sources = [
           '__init__.py',
           '../client.py',
           '../disc_utils.py',
           '../disc_consts.py',
          ]
local_sources_rules = []
for file in local_sources:
    local_sources_rules.append(env.Install("discoveryclient", "#controller/src/discovery/client/" + file))

sandesh_gen_py_gfiles = env.SandeshGenPy('discovery_client.sandesh', 'discoveryclient/sandesh/', False)

cd_cmd = 'cd ' + Dir('.').path + ' && '
sdist_depends = [generated_rule]
sdist_depends.extend(setup_sources_rules)
sdist_depends.extend(local_sources_rules)
sdist_depends.extend(sandesh_gen_py_gfiles)
sdist_gen = env.Command('dist/discoveryclient-0.1dev.tar.gz',
                        'setup.py', cd_cmd + 'python setup.py sdist')

env.Default(sdist_gen)

if 'install' in BUILD_TARGETS:
    install_cmd = env.Command(None,
                              'setup.py',
                              cd_cmd + 'python setup.py install %s' %
                              env['PYTHON_INSTALL_OPT'])
    env.Depends(install_cmd, sdist_depends)
    env.Alias('install', install_cmd)



env.Depends(generated_rule, [autogen_infra_sources, autogen_sources, local_sources_rules])
env.Depends(local_sources_rules, autogen_infra_sources)

# install everything before building distribution
env.Depends(sdist_gen, sdist_depends)
env.Alias('src/discovery:client', sdist_gen)
