#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import platform
if platform.system() == 'Darwin':
    Return()

Import('AgentEnv')
env = AgentEnv.Clone()

SandeshGenFiles = env.SandeshGenCpp('diag.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)
sandesh_objs = AgentEnv.BuildExceptionCppObj(env, SandeshGenSrcs)

libdiag = env.Library('diag',
                   sandesh_objs +
                   [
                    'diag.cc',
                    'diag_proto.cc',
                    'ping.cc',
                    'traceroute.cc',
                    'overlay_ping.cc',
                    'overlay_traceroute.cc',
                    'diag_pkt_handler.cc',
                    'segment_health_check.cc'
                   ])

env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
