#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
if sys.platform == 'darwin':
    Return()

Import('AgentEnv')
env = AgentEnv.Clone()

SandeshGenFiles = env.SandeshGenCpp('diag.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)
sandesh_objs = AgentEnv.BuildExceptionCppObj(env, SandeshGenSrcs)

libdiag = env.Library('diag',
                   sandesh_objs +
                   [
                    'diag.cc',
                    'ping.cc',
                    'diag_pkt_handler.cc'
                   ])

#.de.TOFIX disabling tests
#env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
