#
# Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])

libbgp_inet6vpn = env.Library('bgp_inet6vpn',
                              [
                               'inet6vpn_table.cc',
                               'inet6vpn_route.cc'
                               ])

inet6vpn_test_cases = env.SConscript('test/SConscript', exports='BuildEnv',
                                     duplicate = 0)
Return('inet6vpn_test_cases')
