#
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
# agent_map directory

import sys
if sys.platform == 'darwin':
    Return()

Import('GmpEnv')
env = GmpEnv.Clone()

except_env = env.Clone()
cflags = except_env['CCFLAGS']
if '-fno-exceptions' in cflags:
   cflags.remove('-fno-exceptions')
except_env.Replace(CCFLAGS=cflags)

libagent_map = env.Library('agent_map',
                    [
                    'task_block_api.cc',
                    'task_thread_api.cc',
                    'task_timer_api.cc',
                    'patricia_api.cc',
                    'gmpx_environment.c',
                     ])

