#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
import re
Import('AgentEnv')
env = AgentEnv.Clone()

AgentEnv.MakeTestEnv(env)

init_test_suite = []
init_flaky_test_suite = []
test_agent_init = AgentEnv.MakeTestCmd(env, 'test_agent_init', init_test_suite)
env.Alias('agent:test_agent_init', test_agent_init)
test_vmware = AgentEnv.MakeTestCmd(env, 'test_vmware', init_test_suite)

test = env.TestSuite('agent-test', init_test_suite)
env.Alias('agent:init', test)
env.Alias('controller/src/vnsw/agent/init:test', test)

flaky_test = env.TestSuite('agent-flaky-test', init_flaky_test_suite)
env.Alias('controller/src/vnsw/agent/init:flaky_test', flaky_test)

Return('init_test_suite')
