# -*- mode: python; -*-
import os
import platform
import sys

libnl_dir = str(Dir('#/third_party/libnl-3.2.25/'))
libpcap_dir = str(Dir('#/third_party/libpcap-1.7.4/'))
tcpdump_dir  = str(Dir('#/third_party/tcpdump-4.7.4/'))
build_dir = str(Dir('#/build'))
libnl_libs = build_dir + '/lib'

env = DefaultEnvironment()
bin_dir = str(Dir('#/build/sbin/'))

config_opts = '--prefix=' + build_dir

cmd = ('(cd ' + libnl_dir + '; ' +
  './configure ' + config_opts +'; make; make install;' +
  ' cd ' + libpcap_dir + '; ' +
  './configure LDFLAGS=\"-L' + libnl_libs + '\" ' + config_opts +'; make; make install;' +
  'cd ' + tcpdump_dir + ';' +
  './configure LDFLAGS=\"-L' + libnl_libs + '\" ' + config_opts +'; make; make install;' +
  'mv ' + bin_dir + '/tcpdump ' + bin_dir + '/contrail-tcpdump)')

binproducts = [ str(File('#/build/sbin/contrail-tcpdump')) ]

if not os.path.exists(tcpdump_dir + '/Makefile'):
    Execute(cmd)

env.Alias('install', env.Install(env['INSTALL_BIN'], binproducts))
