#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()

libtunnel_encap = env.Library('tunnel_encap', ['tunnel_encap.cc'])

tunnelencap_test_cases = env.SConscript('test/SConscript', exports='BuildEnv',
                                    duplicate = 0)
Return('tunnelencap_test_cases')
