# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
import os

Import('CfgmEnv')
env = CfgmEnv.Clone()

gobin = env.GoCniBuild('mesos_cni')

env.Alias('contrail-mesos-cni', gobin)
env.Alias('install', env.InstallAs(env['INSTALL_BIN'] + '/contrail-mesos-cni', gobin))
env.Default(gobin)
