#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
# services directory

import sys
if sys.platform == 'darwin':
    Return()

Import('AgentEnv')
env = AgentEnv.Clone()

except_env = env.Clone()
cflags = except_env['CCFLAGS']
if '-fno-exceptions' in cflags:
   cflags.remove('-fno-exceptions')
except_env.Replace(CCFLAGS=cflags)

env.Append(CPPPATH = '../common')
env.Append(CPPPATH = '../gmp_map')
env.Append(CPPPATH = '../agent_map')
env.Append(CPPPATH = '../stubs/bitvector')

libgrpmgmt = env.Library('grpmgmt',
                     [
                      'gmp_addrlist.c',
                      'gmpp_proto.c',
                      'gmpr_client.c',
                      'gmpr_engine.c',
                      'gmpr_group.c',
                      'gmpr_host.c',
                      'gmpr_instance.c',
                      'gmpr_intf.c',
                      'gmp_router.c',
                      'gmpr_trace.c',
                      'gmp_trace.c',
                      'igmp_protocol.c',
                      ])

