# -*- mode: python; -*-
import platform

subdirs = [
    'bind',
    'gunit',
    'hiredis',
    'http_parser',
    'pugixml',
    'rapidjson',
    'thrift',
]

(distname, version, _) = platform.dist()
if distname != 'Ubuntu' or float(version) < 14.04:
    subdirs += [
        'boost',
        'curl-7.24.0',
        'gperftools',
        'libxml2', 
        'log4cplus',
        'tbb',
        'icu',
    ]

for dir in subdirs:
    SConscript(dirs = dir, variant_dir = '#/build/third_party/' + dir)
