#!/bin/bash
#
# Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
#
# Gets dpkg data and displays the name, version & build-id
# build-id could be one of:
# build number - if the package was installed from an ISO
# repo name - if the package was installed/updated from an debian repository
# RPM name - if the package was intalled locally (rpm install or yum localinstall)
# Example output
# contrail-analytics                     1-1304082216        148                 
# openstack-dashboard.noarch             2012.1.3-1.fc17     updates             
# contrail-agent                         1-1304091654        contrail-agent-1-1304091654.x86_64

TMPFILE=/tmp/yl.${BASHPID}
CONTRAILRPMS=/etc/contrail/debs_list.txt
VERSIONFILE=/opt/contrail/contrail_packages/VERSION
# CONTRAIL_INSTALLS="contrail_install_repo"
CONTRAIL_INSTALLS="Installed:"

# Installs variable - BUILDID in the env
if [ -f $VERSIONFILE ];
then
    source $VERSIONFILE
fi

# get all install packages
dpkg --list >> /tmp/installed_pkgs

echo "Package                                Version                 Build-ID | Repo | Package Name"
echo "-------------------------------------- ----------------------- ----------------------------------"
for i in `cat $CONTRAILRPMS`; do
    version=$(grep "$i " /tmp/installed_pkgs | awk '/^.i/ { print $3 }')
    if [[ -n $version ]]; then
        buildid=$(echo $version | cut -d "-" -f2)
        version=$(echo $version | cut -d "-" -f1-2)
        printf "%-39s%-31s%-20s\n" $i $version $buildid
    fi
    unset version buildid
done
