#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')
import sys

env = BuildEnv.Clone()

env.Append(CPPPATH = env['TOP'])

env.Append(LIBPATH = env['TOP'] + '/base')
env.Append(LIBPATH = env['TOP'] + '/base/test')
env.Append(LIBPATH = env['TOP'] + '/bgp')
env.Append(LIBPATH = env['TOP'] + '/bgp/inet')
env.Append(LIBPATH = env['TOP'] + '/bgp/inetmcast')
env.Append(LIBPATH = env['TOP'] + '/bgp/enet')
env.Append(LIBPATH = env['TOP'] + '/bgp/evpn')
env.Append(LIBPATH = env['TOP'] + '/bgp/test')
env.Append(LIBPATH = env['TOP'] + '/bgp/l3vpn')
env.Append(LIBPATH = env['TOP'] + '/bgp/routing-instance')
env.Append(LIBPATH = env['TOP'] + '/bgp/rtarget')
env.Append(LIBPATH = env['TOP'] + '/bgp/security_group')
env.Append(LIBPATH = env['TOP'] + '/bgp/tunnel_encap')
env.Append(LIBPATH = env['TOP'] + '/control-node')
env.Append(LIBPATH = env['TOP'] + '/db')
env.Append(LIBPATH = env['TOP'] + '/io')
env.Append(LIBPATH = env['TOP'] + '/ifmap')
env.Append(LIBPATH = env['TOP'] + '/net')
env.Append(LIBPATH = env['TOP'] + '/route')
env.Append(LIBPATH = env['TOP'] + '/xmpp')
env.Append(LIBPATH = env['TOP'] + '/xml')
env.Append(LIBPATH = env['TOP'] + '/schema')

env.Prepend(LIBS = [
                    'task_test',
                    'bgptest',
                    'bgp',
                    'control_node',
                    'peer_sandesh',
                    'routing_instance',
                    'rtarget',                    
                    'security_group',                    
                    'tunnel_encap',                    
                    'bgp_schema',
                    'sandesh',
                    'http',
                    'http_parser',
                    'curl',
                    'ifmap_server',
                    'ifmap_common',
                    'base',
                    'db',
                    'gunit',
                    'io',
                    'sandeshvns',
                    'net',
                    'route',
                    'xmpp',
                    'bgp_inet',
                    'bgp_inetmcast',
                    'bgp_enet',
                    'bgp_evpn',
                    'bgp_l3vpn',
                    'bgp_l3vpn_unicast',
                    'bgp_l3vpn_multicast',
                    'bgp_l3vpn_multicast_msg',
                    'xmpp_enet',
                    'xml',
                    'pugixml',
                    'boost_regex'
                    ])

if sys.platform != 'darwin':
    env.Append(LIBS=['rt'])
    env.Prepend(LINKFLAGS = ['-Wl,--whole-archive',
                             '-lbgp_inet',
                             '-lbgp_inetmcast',
                             '-lbgp_enet',
                             '-lbgp_evpn',
                             '-lbgp_l3vpn',
                             '-ltask_test',
                             '-Wl,--no-whole-archive'])
else:
    lib_inet = Dir('../../inet').path + '/libbgp_inet.a'
    env.Prepend(LINKFLAGS = ['-Wl,-force_load,' + lib_inet])
    lib_inetmcast = Dir('../../inetmcast').path + '/libbgp_inetmcast.a'
    env.Prepend(LINKFLAGS = ['-Wl,-force_load,' + lib_inetmcast])
    lib_enet = Dir('../../enet').path + '/libbgp_enet.a'
    env.Prepend(LINKFLAGS = ['-Wl,-force_load,' + lib_enet])
    lib_evpn = Dir('../../evpn').path + '/libbgp_evpn.a'
    env.Prepend(LINKFLAGS = ['-Wl,-force_load,' + lib_evpn])
    lib_l3vpn = Dir('../../l3vpn').path + '/libbgp_l3vpn.a'
    env.Prepend(LINKFLAGS = ['-Wl,-force_load,' + lib_l3vpn])

evpn_table_test = env.Program('evpn_table_test', ['evpn_table_test.cc'])
env.Alias('src/bgp/evpn:evpn_table_test', evpn_table_test)

evpn_prefix_test = env.Program('evpn_prefix_test', ['evpn_prefix_test.cc'])
env.Alias('src/bgp/evpn:evpn_prefix_test', evpn_prefix_test)

test_suite = [
    evpn_prefix_test,
    evpn_table_test,
]

test = env.TestSuite('bgp-test', test_suite)
env.Alias('src/bgp:test', test)

Return('test_suite')
