#!/usr/bin/env python


import sys
import vnc_cfg_api_server
sys.path.append(vnc_cfg_api_server.__path__[0])
from vnc_cfg_api_server.vnc_cfg_api_server import main

if __name__ == "__main__":
   import cgitb
   cgitb.enable(format='text')
   main()
