import os
import sys

rapidjson_headers = [
    'rapidjson/stream.h',
    'rapidjson/istreamwrapper.h',
    'rapidjson/memorybuffer.h',
    'rapidjson/prettywriter.h',
    'rapidjson/memorystream.h',
    'rapidjson/ostreamwrapper.h',
    'rapidjson/encodedstream.h',
    'rapidjson/pointer.h',
    'rapidjson/stringbuffer.h',
    'rapidjson/writer.h',
    'rapidjson/allocators.h',
    'rapidjson/filewritestream.h',
    'rapidjson/reader.h',
    'rapidjson/fwd.h',
    'rapidjson/encodings.h',
    'rapidjson/document.h',
    'rapidjson/schema.h',
    'rapidjson/filereadstream.h',
    'rapidjson/rapidjson.h',
    'rapidjson/internal/biginteger.h',
    'rapidjson/internal/diyfp.h',
    'rapidjson/internal/dtoa.h',
    'rapidjson/internal/ieee754.h',
    'rapidjson/internal/itoa.h',
    'rapidjson/internal/meta.h',
    'rapidjson/internal/pow10.h',
    'rapidjson/internal/regex.h',
    'rapidjson/internal/stack.h',
    'rapidjson/internal/strfunc.h',
    'rapidjson/internal/strtod.h',
    'rapidjson/internal/swap.h',
    'rapidjson/error/error.h',
    'rapidjson/error/en.h',
    'rapidjson/msinttypes/inttypes.h',
    'rapidjson/msinttypes/stdint.h',

]

for hdr in rapidjson_headers:
    Command('#build/include/' + hdr, [], \
            Copy("$TARGET", File('#third_party/rapidjson/include/' + hdr)))

# Local Variables:
# mode: python
# End:
