#
# Copyright (c) 2015 Juniper Networks, Inc. All rights reserved.
#

Import('AgentEnv')
env = AgentEnv.Clone()

subdirs = [
    'flow_stats',
    'ksync',
    'stats_collector',
]

for dir in subdirs:
    env.SConscript(dir + '/SConscript', exports=['AgentEnv'], duplicate=0)
