#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])

libbgp_inetmcast = env.Library('bgp_inetmcast',
                       ['inetmcast_route.cc',
                        'inetmcast_table.cc'
                        ])

env.SConscript('test/SConscript', exports='BuildEnv', duplicate = 0)
