#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

except_files = [ 'cfg_vgw.cc' ]
except_objs = AgentEnv.BuildExceptionCcObj(env, except_files)

libvgw = env.Library('libvgw',
                      except_objs +
                      [ 'vgw.cc' ])

env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
