# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('CfgmEnv')
env = CfgmEnv.Clone()

# Generate the sandesh UVE source files
SandeshGenPyFiles  = env.SandeshGenPy('virtual_machine.sandesh')
SandeshGenPyFiles += env.SandeshGenPy('virtual_network.sandesh')
SandeshGenPyFiles += env.SandeshGenPy('vnc_api.sandesh')
SandeshGenPyFiles += env.SandeshGenPy('acl.sandesh')
SandeshGenPyFiles += env.SandeshGenPy('service_instance.sandesh')
SandeshGenPyFiles += env.SandeshGenPy('cfgm_cpuinfo.sandesh')
