#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
Import('AgentEnv')
env = AgentEnv.Clone()

import sys
SandeshGenFiles = env.SandeshGenCpp('controller.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)

except_env = AgentEnv.Clone()
cflags = except_env['CCFLAGS']

sandesh_objs = []
for src in SandeshGenSrcs:                    
    objname = src.replace('.cpp', '.o')
    obj = env.Object(objname, src)
    sandesh_objs.append(obj)

vnswctrl = env.Library('vnswctrl',
                       sandesh_objs +
                       [
                          'controller_init.cc',
                          'controller_cleanup_timer.cc',
                          'controller_export.cc',
                          'controller_ifmap.cc',
                          'controller_peer.cc',
                          'controller_route_walker.cc',
                          'controller_vrf_export.cc',
                          'controller_dns.cc',
                          'controller_sandesh.cc'
                       ])
