#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
Import('AgentEnv')
env = AgentEnv.Clone()

import sys
SandeshGenFiles = env.SandeshGenCpp('controller.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)
sandesh_objs = AgentEnv.BuildExceptionCppObj(env, SandeshGenSrcs)

vnswctrl = env.Library('vnswctrl',
                       sandesh_objs +
                       [
                          'controller_init.cc',
                          'controller_cleanup_timer.cc',
                          'controller_export.cc',
                          'controller_ifmap.cc',
                          'controller_peer.cc',
                          'controller_route_path.cc',
                          'controller_route_walker.cc',
                          'controller_vrf_export.cc',
                          'controller_dns.cc',
                          'controller_sandesh.cc'
                       ])
