#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('AgentEnv')
env = AgentEnv.Clone()

env.Prepend(LIBS=['gunit'])
cflags = env['CCFLAGS']
cflags.append('-Wno-return-type')
if '-fno-exceptions' in cflags:
    cflags.remove('-fno-exceptions')
    env.Replace(CCFLAGS = cflags)

env.Append(LIBPATH=['../../test'])
env.Prepend(LIBS=['agent_test']);
env.Append(LIBS=['agent_test_buildinfo'])

import sys
test = env.Program(target = 'test', source = ['test.cc'])
env.Alias('controller/src/vnsw/agent/cmn:test', test)

test_subop = env.Program(target = 'test_subop', source = ['test_subop.cc'])
env.Alias('agent:test_subop', test_subop)

test_agent_init = env.Program(target = 'test_agent_init', 
                              source = ['test_agent_init.cc'])
env.Alias('agent:test_agent_init', test_agent_init)

test_vmware = env.Program(target = 'test_vmware',
                          source = ['test_vmware.cc'])
env.Alias('agent:test_vmware', test_vmware)

agent_init_suite = [test_agent_init, test_vmware, test_subop]

test = env.TestSuite('agent-test', agent_init_suite)
env.Alias('src/vnsw/agent:test', test)
Return('agent_init_suite')
