#
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])

libbgp_mvpn = env.Library('bgp_mvpn',
                            ['mvpn_route.cc', 'mvpn_table.cc'])

mvpn_unit_tests = env.SConscript('test/SConscript', exports='BuildEnv',
                                   duplicate = 0)
Return('mvpn_unit_tests')
