#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
import re
Import('AgentEnv')
env = AgentEnv.Clone()

AgentEnv.MakeTestEnv(env)

service_test_suite = []
service_flaky_test_suite = []

dhcp_test = AgentEnv.MakeTestCmd(env, 'dhcp_test', service_test_suite)
env.Alias('src/vnsw:dhcp_test', dhcp_test)
dns_test = AgentEnv.MakeTestCmd(env, 'dns_test', service_test_suite)
env.Alias('src/vnsw:dns_test', dns_test)
dns_resolver_test = AgentEnv.MakeTestCmd(env, 'dns_resolver_test', 
                                         service_test_suite)
env.Alias('src/vnsw:dns_resolver_test', dns_resolver_test)
arp_test = AgentEnv.MakeTestCmd(env, 'arp_test', service_test_suite)
icmp_test = AgentEnv.MakeTestCmd(env, 'icmp_test', service_test_suite)
igmp_test = AgentEnv.MakeTestCmd(env, 'igmp_test', service_test_suite)
igmp_query_test = AgentEnv.MakeTestCmd(env, 'igmp_query_test', service_test_suite)
igmp_vn_cfg_test = AgentEnv.MakeTestCmd(env, 'igmp_vn_cfg_test', service_test_suite)
env.Alias('vnsw/agent/igmp_vn_cfg_test', igmp_vn_cfg_test)
igmp_mvpn_test = AgentEnv.MakeTestCmd(env, 'igmp_mvpn_test', service_test_suite)
igmp_evpn_test = AgentEnv.MakeTestCmd(env, 'igmp_evpn_test', service_test_suite)
igmp_mpolicy_test = AgentEnv.MakeTestCmd(env, 'igmp_mpolicy_test', service_test_suite)
icmpv6_test = AgentEnv.MakeTestCmd(env, 'icmpv6_test', service_test_suite)
metadata_test = AgentEnv.MakeTestCmd(env, 'metadata_test', service_test_suite)
pkt_trace_test = AgentEnv.MakeTestCmd(env, 'pkt_trace_test', service_test_suite)
arp_path_preference_test = AgentEnv.MakeTestCmd(env, 'arp_path_preference_test',
                                                service_test_suite)
icmpv6_path_preference_test = AgentEnv.MakeTestCmd(env, 'icmpv6_path_preference_test',
                                                  service_test_suite)
flaky_test = env.TestSuite('agent-flaky-test', service_flaky_test_suite)
env.Alias('controller/src/vnsw/agent/services:flaky_test', flaky_test)

test = env.TestSuite('agent-test', service_test_suite)
env.Alias('agent:services', test)
env.Alias('controller/src/vnsw/agent/services:test', test)
Return('service_test_suite')
