#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
import re
Import('AgentEnv')
env = AgentEnv.Clone()

AgentEnv.MakeTestEnv(env)

service_test_suite = []
service_flaky_test_suite = []

dhcp_test = AgentEnv.MakeTestCmd(env, 'dhcp_test', service_test_suite)
dns_test = AgentEnv.MakeTestCmd(env, 'dns_test', service_test_suite)
arp_test = AgentEnv.MakeTestCmd(env, 'arp_test', service_test_suite)
icmp_test = AgentEnv.MakeTestCmd(env, 'icmp_test', service_test_suite)
metadata_test = AgentEnv.MakeTestCmd(env, 'metadata_test', service_test_suite)
pkt_trace_test = AgentEnv.MakeTestCmd(env, 'pkt_trace_test', service_test_suite)

flaky_test = env.TestSuite('agent-flaky-test', service_flaky_test_suite)
env.Alias('controller/src/vnsw/agent/services:flaky_test', flaky_test)

test = env.TestSuite('agent-test', service_test_suite)
env.Alias('agent:services', test)
env.Alias('controller/src/vnsw/agent/services:test', test)
Return('service_test_suite')
