#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

except_env = env.Clone()
cflags = except_env['CCFLAGS']
if '-fno-exceptions' in cflags:
    cflags.remove('-fno-exceptions')
    except_env.Replace(CCFLAGS = cflags)

except_files = [ 'agent_param.cc' ]
except_objs = []
for except_src in except_files:
    objname = except_src.replace('.cc', '.o')
    obj = except_env.Object(objname, except_src)
    except_objs.append(obj)

vnswcmn_sources = ['agent.cc', 'agent_db.cc', 'agent_factory.cc',
                   'agent_stats.cc']

vnswcmn = env.Library('vnswcmn', except_objs + vnswcmn_sources)

env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
