#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

SandeshGenFiles = env.SandeshGenCpp('stats.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)
sandesh_objs = AgentEnv.BuildExceptionCppObj(env, SandeshGenSrcs)

vnswcmn_sources = ['agent.cc', 'agent_db.cc', 'agent_factory.cc',
                   'agent_signal.cc', 'agent_stats.cc', 'event_notifier.cc']

vnswcmn = env.Library('vnswcmn', sandesh_objs + vnswcmn_sources)

env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
