# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('BuildEnv')
env = BuildEnv.Clone()

env.SConscript('contrail-cli/SConscript', exports='BuildEnv', duplicate = 0)
