#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()

liborigin_vn = env.Library('origin_vn', ['origin_vn.cc'])

env.SConscript('test/SConscript', exports='BuildEnv', duplicate = 0)
