#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
import re
Import('AgentEnv')
env = AgentEnv.Clone()

AgentEnv.MakeTestEnv(env)

ksync_test_suite = []
ksync_flaky_test_suite = []

test_vnswif = AgentEnv.MakeTestCmd(env, 'test_vnswif', ksync_test_suite)

flaky_test = env.TestSuite('agent-flaky-test', ksync_flaky_test_suite)
env.Alias('controller/src/vnsw/agent/ksync:flaky_test', flaky_test)

test = env.TestSuite('agent-test', ksync_test_suite)
env.Alias('agent:ksync', test)
env.Alias('controller/src/vnsw/agent/ksync:test', test)
Return('ksync_test_suite')
