#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
# services directory
import sys

if sys.platform == 'darwin':
    Return()

Import('AgentEnv')
env = AgentEnv.Clone()

SandeshGenFiles = env.SandeshGenCpp('services.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)
sandesh_objs = AgentEnv.BuildExceptionCppObj(env, SandeshGenSrcs)

libservices = env.Library('agent_services',
                     sandesh_objs +
                     [
                      'arp_entry.cc',
                      'arp_handler.cc',
                      'arp_proto.cc',
                      'dhcp_handler.cc',
                      'dhcp_proto.cc',
                      'dns_handler.cc',
                      'dns_proto.cc',
                      'icmp_handler.cc',
                      'icmp_proto.cc',
                      'icmp_error_handler.cc',
                      'icmp_error_proto.cc',
                      'metadata_proxy.cc',
                      'services_init.cc',
                      'services_sandesh.cc',
                      ])
env.Requires('metadata_proxy.o', '#build/include/isc')

env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
