#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
import re
Import('AgentEnv')
env = AgentEnv.Clone()

AgentEnv.MakeTestEnv(env)

diag_test_suite = []
test_ping = AgentEnv.MakeTestCmd(env, 'test_ping', diag_test_suite)

test = env.TestSuite('agent-test', diag_test_suite)
env.Alias('agent:diag', test)
Return('diag_test_suite')
