# -*- mode: python; -*- 
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#


Import('BuildEnv')
import sys
env = BuildEnv.Clone()

env.Append(LIBPATH = ['#/' + Dir('..').path, 
                      '../../../base',
                      '../../../base/test',
                      '../../../control-node',
                      '../../discovery/client',
                      '../../../io',
                      '../../../schema',
                      '../../../xml',
                      '../../http/client'
                      ])
                  
env.Prepend(LIBS = ['ds', 'services', 'task_test', 'xml', 'pugixml', 
                    'io', 'sandesh', 'io', 'sandeshvns',
                    'httpc', 'http', 'http_parser', 'curl',
                    'process_info',
                    'base', 'gunit', 'boost_regex', 'control_node'])

if sys.platform != 'darwin':
    env.Append(LIBS = ['rt'])

discovery_client_test = env.Program(target = 'discovery_client_test', 
                                    source = ['discovery_client_test.cc'])
env.Alias('src/discovery:client_test', discovery_client_test)

discovery_client_test_suite = [
    discovery_client_test
    ]

test = env.TestSuite('discovery-client-test', discovery_client_test_suite)
env.Alias('controller/src/discovery:test', test)

Return('discovery_client_test_suite')
