#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import os
import sys

Import('AgentEnv')
env = AgentEnv.Clone()

except_files = [ 'cfg_init.cc' ]
except_objs = AgentEnv.BuildExceptionCcObj(env, except_files)

libcfg = env.Library('cfg',
                     except_objs +
                     ['cfg_filter.cc',
                      'cfg_mirror.cc',
                      'discovery_agent.cc',
                      ])
