#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')
env = BuildEnv.Clone()

vpath = '#/src/docs/opserver'

build_dir = str(Dir('.').abspath)+'/doc'
build_dir_doctrees = build_dir+'/doctrees'
build_dir_html = build_dir+'/html'

cmd = ('(sphinx-build -b html -d ' + build_dir_doctrees + ' ' + str(Dir(vpath).abspath) + ' ' + build_dir_html + ')')

docs = env.Command('doc', str(Dir(vpath)), cmd)

env.AlwaysBuild(docs)
