# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('BuildEnv')

import sys

env = BuildEnv.Clone()

BuildEnv.SConscript(dirs=['contrail-vrouter-api'],
                    exports='BuildEnv',
                    variant_dir='#build/noarch/contrail-vrouter-api',
                    duplicate=1)

subdirs = ['agent',
]

for dir in subdirs:
    env.SConscript(dir + '/SConscript', exports='BuildEnv',
                   variant_dir=BuildEnv['TOP'] + '/vnsw/' + dir,
                   duplicate=0)

env.Alias('controller/src/agent:test', [
    'controller/src/vnsw/agent/cmn:test',
    'controller/src/vnsw/agent/diag:test',
#   'controller/src/vnsw/agent/filter:test',
    'controller/src/vnsw/agent/init:test',
    'controller/src/vnsw/agent/kstate:test',
    'controller/src/vnsw/agent/ksync:test',
    'controller/src/vnsw/agent/openstack:test',
    'controller/src/vnsw/agent/oper:test',
    'controller/src/vnsw/agent/pkt:test',
    'controller/src/vnsw/agent/services:test',
    'controller/src/vnsw/agent:test',
    'controller/src/vnsw/agent/uve:test',
    'controller/src/vnsw/agent/vgw:test',
])
