# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('BuildEnv')

import sys

env = BuildEnv.Clone()

BuildEnv.SConscript(dirs=['contrail-vrouter-api'],
                    exports='BuildEnv',
                    variant_dir='#build/noarch/contrail-vrouter-api',
                    duplicate=1)

subdirs = ['agent',
]

for dir in subdirs:
    env.SConscript(dir + '/SConscript', exports='BuildEnv',
                   variant_dir=BuildEnv['TOP'] + '/vnsw/' + dir,
                   duplicate=0)
