#
# Copyright (c) 2018 Juniper Networks, Inc. All rights reserved.
#

import subprocess

env = DefaultEnvironment()

vpath = '#third_party/cmocka-1.1.2'
working_dir = Dir('.').abspath

def build_cmocka(target, source, env):
    env.EnsureBuildDependency('cmake')

    cmake_flags = [
        '-DWITH_STATIC_LIB=ON',
        '-DUNIT_TESTING=OFF',
        '-DCMAKE_GENERATOR_PLATFORM=x64',
        '-DCMAKE_INSTALL_PREFIX=' + Dir('#build').abspath,
    ]

    subprocess.call(['cmake'] + cmake_flags + [Dir(vpath).abspath], cwd=working_dir)
    subprocess.call(['cmake', '--build', '.', '--target', 'install', '--config', env['VS_BUILDMODE']], cwd=working_dir)

products = [
    File('#build/include/cmocka.h'),
    File('#build/lib/cmocka.lib'),
]

env.Command(products, Dir(vpath), build_cmocka)
