#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.CppDisableExceptions()
env.Append(CPPPATH = [env['TOP']])

SandeshGenFiles = env.SandeshGenCpp('io.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)

except_env = BuildEnv.Clone()
except_env.Append(CPPPATH = env['TOP_INCLUDE'] + '/thrift')
except_env.Append(CPPPATH = [env['TOP']])
EventManagerSrc = except_env.Object('event_manager.o', 'event_manager.cc')
SslServerSrc = except_env.Object('ssl_server.o', 'ssl_server.cc')

usock_env = BuildEnv.Clone()
usock_env.CppEnableExceptions()
usock_env.Append(CPPPATH = env['TOP'])
usock_server = usock_env.Object('usock_server.o', 'usock_server.cc')

libio = env.Library('io',
            SandeshGenSrcs +
            EventManagerSrc +
            SslServerSrc +
            [
             'io_utils.cc',
             'ssl_session.cc',
             'tcp_message_write.cc',
             'tcp_server.cc',
             'tcp_session.cc',
             'udp_server.cc',
             'usock_server',
            ])

env.SConscript('test/SConscript', exports='BuildEnv', duplicate = 0)
