#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import re

Import('AgentEnv')
env = AgentEnv.Clone()

env.Prepend(CPPPATH = env['TOP'] + '/vnsw/agent/test')
env.Prepend(LIBS=['gunit'])
env.Prepend(CCFLAGS = ['-Wno-return-type', '-Wno-unused-function'])

import sys
if sys.platform != 'darwin':
    env.Append(LIBPATH=['../../test'])
    env.Prepend(LIBS=['agent_test'])
    env.Append(LIBS=['agent_test_buildinfo'])

    test_kstate = env.Program(target = 'test_kstate', source = ['test_kstate.cc'])
    env.Alias('agent:test_kstate', test_kstate)

    test_sandesh_kstate = env.Program(target = 'test_sandesh_kstate', source = ['test_sandesh_kstate.cc', '../../pkt/test/test_pkt_util.o'])
    env.Alias('agent:test_sandesh_kstate', test_sandesh_kstate)

    kstate_test_suite = [
                      test_kstate,
                      test_sandesh_kstate
                      ]
    test = env.TestSuite('agent-test', kstate_test_suite)
    env.Alias('controller/src/vnsw/agent/kstate:test', test)
    Return('kstate_test_suite')
