# -*- mode: python; -*-

#
# Copyright (c) 2019 Juniper Networks, Inc. All rights reserved.
#
import os

Import('BuildEnv')
env = BuildEnv.Clone()

sources = [
    'setup.py',
    'MANIFEST.in',
    'stats/__init__.py',
    'stats/main.py',
    'stats/tests/__init__.py',
    'stats/tests/test_common.py',
    'requirements.txt',
    'test-requirements.txt',
    '.stestr.conf',
    'tox.ini',
]

cd_cmd = 'cd ' + Dir('.').path + ' && '

sdist_gen = env.Command(
    'dist/contrail_stats_client-0.1dev0.zip',
    source_files,
    cd_cmd + 'python setup.py sdist')

env.Alias('controller/src/stats:sdist', sdist_gen)

sdist_depends = []
sdist_depends.extend(env.GetVncAPIPkg())
env.Depends(sdist_gen, sdist_depends)

if 'install' in BUILD_TARGETS:
    install_cmd = env.Command(
        None,
        sources,
        cd_cmd + 'python setup.py install %s' %
        env['PYTHON_INSTALL_OPT'])
    env.Depends(install_cmd, sdist_depends)
    env.Alias('install', install_cmd)

test_target = env.SetupPyTestSuite(
    sdist_gen,
    sdist_depends=[env.GetVncAPIPkg()],
    use_tox=True)

env.Alias('controller/src/stats/stats:test', test_target)
env.Alias('controller/src/stats:test', test_target)
# Local Variables:
# mode: python
# End:
