#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])

libbgp_enet = env.Library('bgp_enet',
                  ['enet_route.cc',
                   'enet_table.cc'
                  ])

enet_unit_tests = env.SConscript('test/SConscript', exports='BuildEnv',
                                 duplicate = 0)
Return('enet_unit_tests')
