#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])
env.Append(CPPPATH = [env['TOP'] + '/bgp'])
env.Append(CPPPATH = [env['TOP'] + '/io'])

# Generate the source files
SandeshGenFiles = env.SandeshGenCpp('routing_instance_analytics.sandesh')
SandeshGenFiles += env.SandeshGenCpp('service_chaining.sandesh')
SandeshGenFiles += env.SandeshGenCpp('static_route.sandesh')
SandeshGenFiles += env.SandeshGenCpp('rtarget_group.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)

librouting_instance = env.Library('routing_instance', SandeshGenSrcs + 
                                         ['peer_manager.cc', 
                                         'routing_instance.cc', 
                                         'routepath_replicator.cc', 
                                         'rtarget_group.cc', 
                                         'rtarget_group_mgr.cc', 
                                         'service_chaining.cc', 
                                         'static_route.cc'])

