#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import re
Import('AgentEnv')
env = AgentEnv.Clone()

# test specific modifications
AgentEnv.MakeTestEnv(env)

uve_test_suite=[]
uve_flaky_test_suite=[]

test_vm_uve = AgentEnv.MakeTestCmdSrc(env, 'test_vm_uve',
                                      [
                                       'test_vm_uve.cc',
                                       '../../pkt/test/test_pkt_util.o'
                                       ],
                                       uve_test_suite)
test_port_bitmap = AgentEnv.MakeTestCmd(env, 'test_port_bitmap', uve_test_suite)
test_stats_mock =  AgentEnv.MakeTestCmd(env, 'test_stats_mock', uve_flaky_test_suite)
test_uve = AgentEnv.MakeTestCmd(env, 'test_uve', uve_flaky_test_suite)

test_vn_uve = AgentEnv.MakeTestCmdSrc(env, 'test_vn_uve', 
                                      [
                                       'test_vn_uve.cc', 
                                       '../../pkt/test/test_pkt_util.o'
                                       ],
                                       uve_flaky_test_suite)
test_vrouter_uve = AgentEnv.MakeTestCmdSrc(env, 'test_vrouter_uve', 
                                           [
                                            'test_vrouter_uve.cc',
                                            '../../pkt/test/test_pkt_util.o'
                                           ],
                                           uve_flaky_test_suite)

flaky_test = env.TestSuite('agent-flaky-test', uve_flaky_test_suite)
env.Alias('controller/src/vnsw/agent/uve:flaky_test', flaky_test)

test = env.TestSuite('agent-test', uve_test_suite)
env.Alias('agent:uve', test)
env.Alias('controller/src/vnsw/agent/uve:test', test)
Return('uve_test_suite')
