#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

SandeshGenFiles = env.SandeshGenCpp('kstate.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)

except_env = AgentEnv.Clone()
cflags = except_env['CCFLAGS']
if '-fno-exceptions' in cflags:
    cflags.remove('-fno-exceptions')
    except_env.Replace(CCFLAGS = cflags)

sandesh_objs = []
for src in SandeshGenSrcs:                    
    objname = src.replace('.cpp', '.o')
    obj = except_env.Object(objname, src)
    sandesh_objs.append(obj)

libkstate = env.Library('kstate',
                        sandesh_objs +
                        ['kstate_handler.cc',
                         'kstate.cc',
                         'kstate_io_context.cc',
                         'interface_kstate.cc',
                         'route_kstate.cc',
                         'nh_kstate.cc',
                         'mpls_kstate.cc',
                         'flow_kstate.cc',
                         'mirror_kstate.cc',
                         'vrf_assign_kstate.cc',
                         'vrf_stats_kstate.cc',
                         'vxlan_kstate.cc',
                         'drop_stats_kstate.cc'
                        ])

# TODO(md): temporarily disabled
#env.SConscript('test/SConscript', exports='AgentEnv', duplicate=0)
