#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

SandeshGenFiles = env.SandeshGenCpp('kstate.sandesh')
SandeshGenSrcs = env.ExtractCpp(SandeshGenFiles)
sandesh_objs = AgentEnv.BuildExceptionCppObj(env, SandeshGenSrcs)

libkstate = env.Library('kstate',
                        sandesh_objs +
                        ['kstate_handler.cc',
                         'kstate.cc',
                         'kstate_io_context.cc',
                         'interface_kstate.cc',
                         'route_kstate.cc',
                         'nh_kstate.cc',
                         'mpls_kstate.cc',
                         'flow_kstate.cc',
                         'mirror_kstate.cc',
                         'vrf_assign_kstate.cc',
                         'vrf_stats_kstate.cc',
                         'vxlan_kstate.cc',
                         'drop_stats_kstate.cc'
                        ])

env.SConscript('test/SConscript', exports='AgentEnv', duplicate=0)
