# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()
env.CppEnableExceptions()

if sys.platform != 'win32':
    vnswnhserver_sources = ['nexthop_client.cc', 'nexthop_server.cc', 'nexthop_manager.cc']
else:
    vnswnhserver_sources = ['windows/nexthop_manager_stub.cc']

vnswnhserver = env.Library('vnswnhserver', vnswnhserver_sources)

env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
